using UnityEngine;
using System.Collections;

public class rotate : MonoBehaviour
{
    public bool goRotate;
	// Use this for initialization
	void Start ()
    {
        goRotate = true;
	}
	
	// Update is called once per frame
	void Update ()
    {
        if (goRotate)
        {
            transform.localRotation = Quaternion.Euler(0.0f, 0.0f, 180.0f);
            
        }
        else
        {
            transform.rotation = Quaternion.identity;
        }
    }

    public void Rotate()
    {
        goRotate = true;
    }
    public void StopRotate()
    {
        goRotate = false;
    }

}
